# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: Deploy to GitHub Pages

# Defines when the workflow will run
on:
  push


jobs:
  # The build job exports marimo notebooks to static HTML/WebAssembly
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      # Check out the repository code
      - name: Export notebooks and build index.html
        uses: jebel-quant/marimushka/actions/export@v0.0.21
        with:
          apps: 'apps'
          notebooks: 'notebooks'
          notebooks_wasm: 'notebooks'
          publish: 'true'
          template: 'templates/tailwind.html.j2'